[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npx serve -s build -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
