[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npx serve -s build -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables for Railway deployment
[[deploy.environmentVariables]]
name = "NODE_ENV"
value = "production"

[[deploy.environmentVariables]]
name = "PORT"
value = "3000"

[[deploy.environmentVariables]]
name = "GENERATE_SOURCEMAP"
value = "false"

[[deploy.environmentVariables]]
name = "CI"
value = "false"